/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Node_H
#define Node_H

#include <TProcessor.h>
#include "mp2_types.h"

namespace mp2 {

class NodeIf {
 public:
  virtual ~NodeIf() {}
  virtual void find_successor(finger_entry& _return, const finger_entry& caller) = 0;
  virtual void closest_preceding_finger(finger_entry& _return, const int32_t id) = 0;
  virtual void get_successor(finger_entry& _return) = 0;
  virtual void get_predecessor(finger_entry& _return) = 0;
  virtual void notify(const finger_entry& n) = 0;
  virtual int32_t add_file(const int32_t key_id, const _FILE& s) = 0;
  virtual int32_t del_file(const int32_t key_id) = 0;
  virtual void get_file(file_data& _return, const int32_t key_id) = 0;
  virtual void get_table(node_table& _return, const int32_t id) = 0;
  virtual bool accept_files(const std::map<int32_t, _FILE> & offload) = 0;
  virtual int32_t dummy_add_file(const _FILE& s) = 0;
  virtual int32_t dummy_del_file(const std::string& key) = 0;
  virtual void dummy_get_file(file_data& _return, const std::string& key) = 0;
};

class NodeIfFactory {
 public:
  typedef NodeIf Handler;

  virtual ~NodeIfFactory() {}

  virtual NodeIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(NodeIf* /* handler */) = 0;
};

class NodeIfSingletonFactory : virtual public NodeIfFactory {
 public:
  NodeIfSingletonFactory(const boost::shared_ptr<NodeIf>& iface) : iface_(iface) {}
  virtual ~NodeIfSingletonFactory() {}

  virtual NodeIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(NodeIf* /* handler */) {}

 protected:
  boost::shared_ptr<NodeIf> iface_;
};

class NodeNull : virtual public NodeIf {
 public:
  virtual ~NodeNull() {}
  void find_successor(finger_entry& /* _return */, const finger_entry& /* caller */) {
    return;
  }
  void closest_preceding_finger(finger_entry& /* _return */, const int32_t /* id */) {
    return;
  }
  void get_successor(finger_entry& /* _return */) {
    return;
  }
  void get_predecessor(finger_entry& /* _return */) {
    return;
  }
  void notify(const finger_entry& /* n */) {
    return;
  }
  int32_t add_file(const int32_t /* key_id */, const _FILE& /* s */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t del_file(const int32_t /* key_id */) {
    int32_t _return = 0;
    return _return;
  }
  void get_file(file_data& /* _return */, const int32_t /* key_id */) {
    return;
  }
  void get_table(node_table& /* _return */, const int32_t /* id */) {
    return;
  }
  bool accept_files(const std::map<int32_t, _FILE> & /* offload */) {
    bool _return = false;
    return _return;
  }
  int32_t dummy_add_file(const _FILE& /* s */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t dummy_del_file(const std::string& /* key */) {
    int32_t _return = 0;
    return _return;
  }
  void dummy_get_file(file_data& /* _return */, const std::string& /* key */) {
    return;
  }
};

typedef struct _Node_find_successor_args__isset {
  _Node_find_successor_args__isset() : caller(false) {}
  bool caller;
} _Node_find_successor_args__isset;

class Node_find_successor_args {
 public:

  Node_find_successor_args() {
  }

  virtual ~Node_find_successor_args() throw() {}

  finger_entry caller;

  _Node_find_successor_args__isset __isset;

  void __set_caller(const finger_entry& val) {
    caller = val;
  }

  bool operator == (const Node_find_successor_args & rhs) const
  {
    if (!(caller == rhs.caller))
      return false;
    return true;
  }
  bool operator != (const Node_find_successor_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_find_successor_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Node_find_successor_pargs {
 public:


  virtual ~Node_find_successor_pargs() throw() {}

  const finger_entry* caller;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_find_successor_result__isset {
  _Node_find_successor_result__isset() : success(false) {}
  bool success;
} _Node_find_successor_result__isset;

class Node_find_successor_result {
 public:

  Node_find_successor_result() {
  }

  virtual ~Node_find_successor_result() throw() {}

  finger_entry success;

  _Node_find_successor_result__isset __isset;

  void __set_success(const finger_entry& val) {
    success = val;
  }

  bool operator == (const Node_find_successor_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Node_find_successor_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_find_successor_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_find_successor_presult__isset {
  _Node_find_successor_presult__isset() : success(false) {}
  bool success;
} _Node_find_successor_presult__isset;

class Node_find_successor_presult {
 public:


  virtual ~Node_find_successor_presult() throw() {}

  finger_entry* success;

  _Node_find_successor_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Node_closest_preceding_finger_args__isset {
  _Node_closest_preceding_finger_args__isset() : id(false) {}
  bool id;
} _Node_closest_preceding_finger_args__isset;

class Node_closest_preceding_finger_args {
 public:

  Node_closest_preceding_finger_args() : id(0) {
  }

  virtual ~Node_closest_preceding_finger_args() throw() {}

  int32_t id;

  _Node_closest_preceding_finger_args__isset __isset;

  void __set_id(const int32_t val) {
    id = val;
  }

  bool operator == (const Node_closest_preceding_finger_args & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    return true;
  }
  bool operator != (const Node_closest_preceding_finger_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_closest_preceding_finger_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Node_closest_preceding_finger_pargs {
 public:


  virtual ~Node_closest_preceding_finger_pargs() throw() {}

  const int32_t* id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_closest_preceding_finger_result__isset {
  _Node_closest_preceding_finger_result__isset() : success(false) {}
  bool success;
} _Node_closest_preceding_finger_result__isset;

class Node_closest_preceding_finger_result {
 public:

  Node_closest_preceding_finger_result() {
  }

  virtual ~Node_closest_preceding_finger_result() throw() {}

  finger_entry success;

  _Node_closest_preceding_finger_result__isset __isset;

  void __set_success(const finger_entry& val) {
    success = val;
  }

  bool operator == (const Node_closest_preceding_finger_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Node_closest_preceding_finger_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_closest_preceding_finger_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_closest_preceding_finger_presult__isset {
  _Node_closest_preceding_finger_presult__isset() : success(false) {}
  bool success;
} _Node_closest_preceding_finger_presult__isset;

class Node_closest_preceding_finger_presult {
 public:


  virtual ~Node_closest_preceding_finger_presult() throw() {}

  finger_entry* success;

  _Node_closest_preceding_finger_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class Node_get_successor_args {
 public:

  Node_get_successor_args() {
  }

  virtual ~Node_get_successor_args() throw() {}


  bool operator == (const Node_get_successor_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Node_get_successor_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_get_successor_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Node_get_successor_pargs {
 public:


  virtual ~Node_get_successor_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_get_successor_result__isset {
  _Node_get_successor_result__isset() : success(false) {}
  bool success;
} _Node_get_successor_result__isset;

class Node_get_successor_result {
 public:

  Node_get_successor_result() {
  }

  virtual ~Node_get_successor_result() throw() {}

  finger_entry success;

  _Node_get_successor_result__isset __isset;

  void __set_success(const finger_entry& val) {
    success = val;
  }

  bool operator == (const Node_get_successor_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Node_get_successor_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_get_successor_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_get_successor_presult__isset {
  _Node_get_successor_presult__isset() : success(false) {}
  bool success;
} _Node_get_successor_presult__isset;

class Node_get_successor_presult {
 public:


  virtual ~Node_get_successor_presult() throw() {}

  finger_entry* success;

  _Node_get_successor_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class Node_get_predecessor_args {
 public:

  Node_get_predecessor_args() {
  }

  virtual ~Node_get_predecessor_args() throw() {}


  bool operator == (const Node_get_predecessor_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Node_get_predecessor_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_get_predecessor_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Node_get_predecessor_pargs {
 public:


  virtual ~Node_get_predecessor_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_get_predecessor_result__isset {
  _Node_get_predecessor_result__isset() : success(false) {}
  bool success;
} _Node_get_predecessor_result__isset;

class Node_get_predecessor_result {
 public:

  Node_get_predecessor_result() {
  }

  virtual ~Node_get_predecessor_result() throw() {}

  finger_entry success;

  _Node_get_predecessor_result__isset __isset;

  void __set_success(const finger_entry& val) {
    success = val;
  }

  bool operator == (const Node_get_predecessor_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Node_get_predecessor_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_get_predecessor_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_get_predecessor_presult__isset {
  _Node_get_predecessor_presult__isset() : success(false) {}
  bool success;
} _Node_get_predecessor_presult__isset;

class Node_get_predecessor_presult {
 public:


  virtual ~Node_get_predecessor_presult() throw() {}

  finger_entry* success;

  _Node_get_predecessor_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Node_notify_args__isset {
  _Node_notify_args__isset() : n(false) {}
  bool n;
} _Node_notify_args__isset;

class Node_notify_args {
 public:

  Node_notify_args() {
  }

  virtual ~Node_notify_args() throw() {}

  finger_entry n;

  _Node_notify_args__isset __isset;

  void __set_n(const finger_entry& val) {
    n = val;
  }

  bool operator == (const Node_notify_args & rhs) const
  {
    if (!(n == rhs.n))
      return false;
    return true;
  }
  bool operator != (const Node_notify_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_notify_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Node_notify_pargs {
 public:


  virtual ~Node_notify_pargs() throw() {}

  const finger_entry* n;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Node_notify_result {
 public:

  Node_notify_result() {
  }

  virtual ~Node_notify_result() throw() {}


  bool operator == (const Node_notify_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Node_notify_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_notify_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Node_notify_presult {
 public:


  virtual ~Node_notify_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Node_add_file_args__isset {
  _Node_add_file_args__isset() : key_id(false), s(false) {}
  bool key_id;
  bool s;
} _Node_add_file_args__isset;

class Node_add_file_args {
 public:

  Node_add_file_args() : key_id(0) {
  }

  virtual ~Node_add_file_args() throw() {}

  int32_t key_id;
  _FILE s;

  _Node_add_file_args__isset __isset;

  void __set_key_id(const int32_t val) {
    key_id = val;
  }

  void __set_s(const _FILE& val) {
    s = val;
  }

  bool operator == (const Node_add_file_args & rhs) const
  {
    if (!(key_id == rhs.key_id))
      return false;
    if (!(s == rhs.s))
      return false;
    return true;
  }
  bool operator != (const Node_add_file_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_add_file_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Node_add_file_pargs {
 public:


  virtual ~Node_add_file_pargs() throw() {}

  const int32_t* key_id;
  const _FILE* s;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_add_file_result__isset {
  _Node_add_file_result__isset() : success(false) {}
  bool success;
} _Node_add_file_result__isset;

class Node_add_file_result {
 public:

  Node_add_file_result() : success(0) {
  }

  virtual ~Node_add_file_result() throw() {}

  int32_t success;

  _Node_add_file_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const Node_add_file_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Node_add_file_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_add_file_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_add_file_presult__isset {
  _Node_add_file_presult__isset() : success(false) {}
  bool success;
} _Node_add_file_presult__isset;

class Node_add_file_presult {
 public:


  virtual ~Node_add_file_presult() throw() {}

  int32_t* success;

  _Node_add_file_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Node_del_file_args__isset {
  _Node_del_file_args__isset() : key_id(false) {}
  bool key_id;
} _Node_del_file_args__isset;

class Node_del_file_args {
 public:

  Node_del_file_args() : key_id(0) {
  }

  virtual ~Node_del_file_args() throw() {}

  int32_t key_id;

  _Node_del_file_args__isset __isset;

  void __set_key_id(const int32_t val) {
    key_id = val;
  }

  bool operator == (const Node_del_file_args & rhs) const
  {
    if (!(key_id == rhs.key_id))
      return false;
    return true;
  }
  bool operator != (const Node_del_file_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_del_file_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Node_del_file_pargs {
 public:


  virtual ~Node_del_file_pargs() throw() {}

  const int32_t* key_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_del_file_result__isset {
  _Node_del_file_result__isset() : success(false) {}
  bool success;
} _Node_del_file_result__isset;

class Node_del_file_result {
 public:

  Node_del_file_result() : success(0) {
  }

  virtual ~Node_del_file_result() throw() {}

  int32_t success;

  _Node_del_file_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const Node_del_file_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Node_del_file_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_del_file_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_del_file_presult__isset {
  _Node_del_file_presult__isset() : success(false) {}
  bool success;
} _Node_del_file_presult__isset;

class Node_del_file_presult {
 public:


  virtual ~Node_del_file_presult() throw() {}

  int32_t* success;

  _Node_del_file_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Node_get_file_args__isset {
  _Node_get_file_args__isset() : key_id(false) {}
  bool key_id;
} _Node_get_file_args__isset;

class Node_get_file_args {
 public:

  Node_get_file_args() : key_id(0) {
  }

  virtual ~Node_get_file_args() throw() {}

  int32_t key_id;

  _Node_get_file_args__isset __isset;

  void __set_key_id(const int32_t val) {
    key_id = val;
  }

  bool operator == (const Node_get_file_args & rhs) const
  {
    if (!(key_id == rhs.key_id))
      return false;
    return true;
  }
  bool operator != (const Node_get_file_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_get_file_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Node_get_file_pargs {
 public:


  virtual ~Node_get_file_pargs() throw() {}

  const int32_t* key_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_get_file_result__isset {
  _Node_get_file_result__isset() : success(false) {}
  bool success;
} _Node_get_file_result__isset;

class Node_get_file_result {
 public:

  Node_get_file_result() {
  }

  virtual ~Node_get_file_result() throw() {}

  file_data success;

  _Node_get_file_result__isset __isset;

  void __set_success(const file_data& val) {
    success = val;
  }

  bool operator == (const Node_get_file_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Node_get_file_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_get_file_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_get_file_presult__isset {
  _Node_get_file_presult__isset() : success(false) {}
  bool success;
} _Node_get_file_presult__isset;

class Node_get_file_presult {
 public:


  virtual ~Node_get_file_presult() throw() {}

  file_data* success;

  _Node_get_file_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Node_get_table_args__isset {
  _Node_get_table_args__isset() : id(false) {}
  bool id;
} _Node_get_table_args__isset;

class Node_get_table_args {
 public:

  Node_get_table_args() : id(0) {
  }

  virtual ~Node_get_table_args() throw() {}

  int32_t id;

  _Node_get_table_args__isset __isset;

  void __set_id(const int32_t val) {
    id = val;
  }

  bool operator == (const Node_get_table_args & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    return true;
  }
  bool operator != (const Node_get_table_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_get_table_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Node_get_table_pargs {
 public:


  virtual ~Node_get_table_pargs() throw() {}

  const int32_t* id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_get_table_result__isset {
  _Node_get_table_result__isset() : success(false) {}
  bool success;
} _Node_get_table_result__isset;

class Node_get_table_result {
 public:

  Node_get_table_result() {
  }

  virtual ~Node_get_table_result() throw() {}

  node_table success;

  _Node_get_table_result__isset __isset;

  void __set_success(const node_table& val) {
    success = val;
  }

  bool operator == (const Node_get_table_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Node_get_table_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_get_table_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_get_table_presult__isset {
  _Node_get_table_presult__isset() : success(false) {}
  bool success;
} _Node_get_table_presult__isset;

class Node_get_table_presult {
 public:


  virtual ~Node_get_table_presult() throw() {}

  node_table* success;

  _Node_get_table_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Node_accept_files_args__isset {
  _Node_accept_files_args__isset() : offload(false) {}
  bool offload;
} _Node_accept_files_args__isset;

class Node_accept_files_args {
 public:

  Node_accept_files_args() {
  }

  virtual ~Node_accept_files_args() throw() {}

  std::map<int32_t, _FILE>  offload;

  _Node_accept_files_args__isset __isset;

  void __set_offload(const std::map<int32_t, _FILE> & val) {
    offload = val;
  }

  bool operator == (const Node_accept_files_args & rhs) const
  {
    if (!(offload == rhs.offload))
      return false;
    return true;
  }
  bool operator != (const Node_accept_files_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_accept_files_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Node_accept_files_pargs {
 public:


  virtual ~Node_accept_files_pargs() throw() {}

  const std::map<int32_t, _FILE> * offload;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_accept_files_result__isset {
  _Node_accept_files_result__isset() : success(false) {}
  bool success;
} _Node_accept_files_result__isset;

class Node_accept_files_result {
 public:

  Node_accept_files_result() : success(0) {
  }

  virtual ~Node_accept_files_result() throw() {}

  bool success;

  _Node_accept_files_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const Node_accept_files_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Node_accept_files_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_accept_files_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_accept_files_presult__isset {
  _Node_accept_files_presult__isset() : success(false) {}
  bool success;
} _Node_accept_files_presult__isset;

class Node_accept_files_presult {
 public:


  virtual ~Node_accept_files_presult() throw() {}

  bool* success;

  _Node_accept_files_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Node_dummy_add_file_args__isset {
  _Node_dummy_add_file_args__isset() : s(false) {}
  bool s;
} _Node_dummy_add_file_args__isset;

class Node_dummy_add_file_args {
 public:

  Node_dummy_add_file_args() {
  }

  virtual ~Node_dummy_add_file_args() throw() {}

  _FILE s;

  _Node_dummy_add_file_args__isset __isset;

  void __set_s(const _FILE& val) {
    s = val;
  }

  bool operator == (const Node_dummy_add_file_args & rhs) const
  {
    if (!(s == rhs.s))
      return false;
    return true;
  }
  bool operator != (const Node_dummy_add_file_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_dummy_add_file_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Node_dummy_add_file_pargs {
 public:


  virtual ~Node_dummy_add_file_pargs() throw() {}

  const _FILE* s;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_dummy_add_file_result__isset {
  _Node_dummy_add_file_result__isset() : success(false) {}
  bool success;
} _Node_dummy_add_file_result__isset;

class Node_dummy_add_file_result {
 public:

  Node_dummy_add_file_result() : success(0) {
  }

  virtual ~Node_dummy_add_file_result() throw() {}

  int32_t success;

  _Node_dummy_add_file_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const Node_dummy_add_file_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Node_dummy_add_file_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_dummy_add_file_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_dummy_add_file_presult__isset {
  _Node_dummy_add_file_presult__isset() : success(false) {}
  bool success;
} _Node_dummy_add_file_presult__isset;

class Node_dummy_add_file_presult {
 public:


  virtual ~Node_dummy_add_file_presult() throw() {}

  int32_t* success;

  _Node_dummy_add_file_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Node_dummy_del_file_args__isset {
  _Node_dummy_del_file_args__isset() : key(false) {}
  bool key;
} _Node_dummy_del_file_args__isset;

class Node_dummy_del_file_args {
 public:

  Node_dummy_del_file_args() : key("") {
  }

  virtual ~Node_dummy_del_file_args() throw() {}

  std::string key;

  _Node_dummy_del_file_args__isset __isset;

  void __set_key(const std::string& val) {
    key = val;
  }

  bool operator == (const Node_dummy_del_file_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const Node_dummy_del_file_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_dummy_del_file_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Node_dummy_del_file_pargs {
 public:


  virtual ~Node_dummy_del_file_pargs() throw() {}

  const std::string* key;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_dummy_del_file_result__isset {
  _Node_dummy_del_file_result__isset() : success(false) {}
  bool success;
} _Node_dummy_del_file_result__isset;

class Node_dummy_del_file_result {
 public:

  Node_dummy_del_file_result() : success(0) {
  }

  virtual ~Node_dummy_del_file_result() throw() {}

  int32_t success;

  _Node_dummy_del_file_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const Node_dummy_del_file_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Node_dummy_del_file_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_dummy_del_file_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_dummy_del_file_presult__isset {
  _Node_dummy_del_file_presult__isset() : success(false) {}
  bool success;
} _Node_dummy_del_file_presult__isset;

class Node_dummy_del_file_presult {
 public:


  virtual ~Node_dummy_del_file_presult() throw() {}

  int32_t* success;

  _Node_dummy_del_file_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Node_dummy_get_file_args__isset {
  _Node_dummy_get_file_args__isset() : key(false) {}
  bool key;
} _Node_dummy_get_file_args__isset;

class Node_dummy_get_file_args {
 public:

  Node_dummy_get_file_args() : key("") {
  }

  virtual ~Node_dummy_get_file_args() throw() {}

  std::string key;

  _Node_dummy_get_file_args__isset __isset;

  void __set_key(const std::string& val) {
    key = val;
  }

  bool operator == (const Node_dummy_get_file_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const Node_dummy_get_file_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_dummy_get_file_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Node_dummy_get_file_pargs {
 public:


  virtual ~Node_dummy_get_file_pargs() throw() {}

  const std::string* key;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_dummy_get_file_result__isset {
  _Node_dummy_get_file_result__isset() : success(false) {}
  bool success;
} _Node_dummy_get_file_result__isset;

class Node_dummy_get_file_result {
 public:

  Node_dummy_get_file_result() {
  }

  virtual ~Node_dummy_get_file_result() throw() {}

  file_data success;

  _Node_dummy_get_file_result__isset __isset;

  void __set_success(const file_data& val) {
    success = val;
  }

  bool operator == (const Node_dummy_get_file_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Node_dummy_get_file_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node_dummy_get_file_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Node_dummy_get_file_presult__isset {
  _Node_dummy_get_file_presult__isset() : success(false) {}
  bool success;
} _Node_dummy_get_file_presult__isset;

class Node_dummy_get_file_presult {
 public:


  virtual ~Node_dummy_get_file_presult() throw() {}

  file_data* success;

  _Node_dummy_get_file_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class NodeClient : virtual public NodeIf {
 public:
  NodeClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  NodeClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void find_successor(finger_entry& _return, const finger_entry& caller);
  void send_find_successor(const finger_entry& caller);
  void recv_find_successor(finger_entry& _return);
  void closest_preceding_finger(finger_entry& _return, const int32_t id);
  void send_closest_preceding_finger(const int32_t id);
  void recv_closest_preceding_finger(finger_entry& _return);
  void get_successor(finger_entry& _return);
  void send_get_successor();
  void recv_get_successor(finger_entry& _return);
  void get_predecessor(finger_entry& _return);
  void send_get_predecessor();
  void recv_get_predecessor(finger_entry& _return);
  void notify(const finger_entry& n);
  void send_notify(const finger_entry& n);
  void recv_notify();
  int32_t add_file(const int32_t key_id, const _FILE& s);
  void send_add_file(const int32_t key_id, const _FILE& s);
  int32_t recv_add_file();
  int32_t del_file(const int32_t key_id);
  void send_del_file(const int32_t key_id);
  int32_t recv_del_file();
  void get_file(file_data& _return, const int32_t key_id);
  void send_get_file(const int32_t key_id);
  void recv_get_file(file_data& _return);
  void get_table(node_table& _return, const int32_t id);
  void send_get_table(const int32_t id);
  void recv_get_table(node_table& _return);
  bool accept_files(const std::map<int32_t, _FILE> & offload);
  void send_accept_files(const std::map<int32_t, _FILE> & offload);
  bool recv_accept_files();
  int32_t dummy_add_file(const _FILE& s);
  void send_dummy_add_file(const _FILE& s);
  int32_t recv_dummy_add_file();
  int32_t dummy_del_file(const std::string& key);
  void send_dummy_del_file(const std::string& key);
  int32_t recv_dummy_del_file();
  void dummy_get_file(file_data& _return, const std::string& key);
  void send_dummy_get_file(const std::string& key);
  void recv_dummy_get_file(file_data& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class NodeProcessor : public ::apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<NodeIf> iface_;
  virtual bool process_fn(apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid, void* callContext);
 private:
  std::map<std::string, void (NodeProcessor::*)(int32_t, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, void*)> processMap_;
  void process_find_successor(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_closest_preceding_finger(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_successor(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_predecessor(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_notify(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_add_file(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_del_file(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_file(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_table(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_accept_files(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_dummy_add_file(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_dummy_del_file(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_dummy_get_file(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  NodeProcessor(boost::shared_ptr<NodeIf> iface) :
    iface_(iface) {
    processMap_["find_successor"] = &NodeProcessor::process_find_successor;
    processMap_["closest_preceding_finger"] = &NodeProcessor::process_closest_preceding_finger;
    processMap_["get_successor"] = &NodeProcessor::process_get_successor;
    processMap_["get_predecessor"] = &NodeProcessor::process_get_predecessor;
    processMap_["notify"] = &NodeProcessor::process_notify;
    processMap_["add_file"] = &NodeProcessor::process_add_file;
    processMap_["del_file"] = &NodeProcessor::process_del_file;
    processMap_["get_file"] = &NodeProcessor::process_get_file;
    processMap_["get_table"] = &NodeProcessor::process_get_table;
    processMap_["accept_files"] = &NodeProcessor::process_accept_files;
    processMap_["dummy_add_file"] = &NodeProcessor::process_dummy_add_file;
    processMap_["dummy_del_file"] = &NodeProcessor::process_dummy_del_file;
    processMap_["dummy_get_file"] = &NodeProcessor::process_dummy_get_file;
  }

  virtual bool process(boost::shared_ptr<apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr<apache::thrift::protocol::TProtocol> poprot, void* callContext);
  virtual ~NodeProcessor() {}
};

class NodeProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  NodeProcessorFactory(const ::boost::shared_ptr< NodeIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< NodeIfFactory > handlerFactory_;
};

class NodeMultiface : virtual public NodeIf {
 public:
  NodeMultiface(std::vector<boost::shared_ptr<NodeIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~NodeMultiface() {}
 protected:
  std::vector<boost::shared_ptr<NodeIf> > ifaces_;
  NodeMultiface() {}
  void add(boost::shared_ptr<NodeIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void find_successor(finger_entry& _return, const finger_entry& caller) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->find_successor(_return, caller);
        return;
      } else {
        ifaces_[i]->find_successor(_return, caller);
      }
    }
  }

  void closest_preceding_finger(finger_entry& _return, const int32_t id) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->closest_preceding_finger(_return, id);
        return;
      } else {
        ifaces_[i]->closest_preceding_finger(_return, id);
      }
    }
  }

  void get_successor(finger_entry& _return) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->get_successor(_return);
        return;
      } else {
        ifaces_[i]->get_successor(_return);
      }
    }
  }

  void get_predecessor(finger_entry& _return) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->get_predecessor(_return);
        return;
      } else {
        ifaces_[i]->get_predecessor(_return);
      }
    }
  }

  void notify(const finger_entry& n) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      ifaces_[i]->notify(n);
    }
  }

  int32_t add_file(const int32_t key_id, const _FILE& s) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->add_file(key_id, s);
      } else {
        ifaces_[i]->add_file(key_id, s);
      }
    }
  }

  int32_t del_file(const int32_t key_id) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->del_file(key_id);
      } else {
        ifaces_[i]->del_file(key_id);
      }
    }
  }

  void get_file(file_data& _return, const int32_t key_id) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->get_file(_return, key_id);
        return;
      } else {
        ifaces_[i]->get_file(_return, key_id);
      }
    }
  }

  void get_table(node_table& _return, const int32_t id) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->get_table(_return, id);
        return;
      } else {
        ifaces_[i]->get_table(_return, id);
      }
    }
  }

  bool accept_files(const std::map<int32_t, _FILE> & offload) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->accept_files(offload);
      } else {
        ifaces_[i]->accept_files(offload);
      }
    }
  }

  int32_t dummy_add_file(const _FILE& s) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->dummy_add_file(s);
      } else {
        ifaces_[i]->dummy_add_file(s);
      }
    }
  }

  int32_t dummy_del_file(const std::string& key) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->dummy_del_file(key);
      } else {
        ifaces_[i]->dummy_del_file(key);
      }
    }
  }

  void dummy_get_file(file_data& _return, const std::string& key) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->dummy_get_file(_return, key);
        return;
      } else {
        ifaces_[i]->dummy_get_file(_return, key);
      }
    }
  }

};

} // namespace

#endif
