// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "MyService.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::mp2;

class MyServiceHandler : virtual public MyServiceIf {
 public:
  MyServiceHandler() {
    // Your initialization goes here

    // nothing is done here in this example
  }

  void an_rpc_func(MyObject& _return, const MyObject& in_object, const int32_t another_arg, const std::vector<std::string> & arg3) {
    // Your implementation goes here
    printf("input object: i=%d, s=%s, d=%f\n", 
	   in_object.i, in_object.s.c_str(), in_object.d);
    for (uint32_t i = 0; i < arg3.size(); ++i) {
      printf("arg3[%u]=%s\n", i, arg3[i].c_str());
    }

    // now I fill out the _return object, which will be returned to
    // the client
    _return.d = in_object.i * in_object.d;
    _return.i = in_object.i * 2;
    _return.s = "the string you sent me was: ";
    _return.s += in_object.s;

    // the client will be waiting.
    sleep(10);

    // NOTE: here you can also be a client and make RPC calls to other
    // servers, or even the client process if it also acts as a server
    // on some port, but be careful to not get into a wait cycle
    // causing a deadlock.
  }

  void another_rpc_func(std::vector<MyObject> & _return) {
    // Your implementation goes here

    printf("another_rpc_func\n");
  }

};

int main(int argc, char **argv) {
  /* server listening on this port */
  int port = 9090;
  shared_ptr<MyServiceHandler> handler(new MyServiceHandler());
  shared_ptr<TProcessor> processor(new MyServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

